It works but NULLS all other values
AppStractSE/PropertyManager pull request #185
Opened 2023-01-11 20:41 UTC by LucBen93

The update "works" but nulls all other values. It's necessary to look over all updates we've created

2023-01-11 21:49 UTC, Zaai90 requested changes

2023-01-11 21:49 UTC, Zaai90 commented on backend/Api/Dto/Requests/CustomerChore/v1/PatchCustomerChoreDto.cs
> +    // public Domain.Domain.Chore Chore { get; set; }
Bortkommenterad kod vill jag helst att vi underviker att pusha till main. Haram hos alla företag så lika bra att ha det som vana. 

Ett bra sätt om man nu vill spara möjlig användbar kod är att man istället gör commit med det som man vill spara och därefter en commit där den är borttagen.

2023-01-11 21:49 UTC, Zaai90 commented on backend/Domain/Features/Commands/CustomerChore/Update/UpdateCustomerChoreCommandHandler.cs
> +        var response = await _repo.UpdateAsync(_mapper.Map<Repository.Entities.CustomerChore>(request));
Detta är tyvärr inte en patch. Det finns lite olika approaches för en skapa en patch. Tänker att vi kan sätta oss tillsammans för att titta på detta.

2023-01-11 21:51 UTC, Zaai90 commented
Bra jobbat för övrigt, vi sätter och tittar på hur vi ska göra våra patches.

2023-01-12 18:40 UTC, LucBen93 commented on backend/Api/Dto/Requests/CustomerChore/v1/PatchCustomerChoreDto.cs
> +    // public Domain.Domain.Chore Chore { get; set; }
Jag lämnade kvar den kommenterade då jag är lite osäker på vad vi vill ha i en request och inte. Jag misstänker att alla id vill vara kvar så att endpointen vet vilken customer och vilket chore  det handlar om, men att Domain.Domain.Periodic Periodic samt Domain.Domain.Chore.Chore inte behöver finnas med? 
Vi kanske kan kika på det samtidigt som vi kikar på hur vi ska göra en bra patch.

2023-01-12 18:40 UTC, LucBen93 commented on backend/Api/Dto/Requests/CustomerChore/v1/PatchCustomerChoreDto.cs
> +    // public Domain.Domain.Chore Chore { get; set; }
> Ett bra sätt om man nu vill spara möjlig användbar kod är att man istället gör commit med det som man vill spara och därefter en commit där den är borttagen.

Det är sant, jag tänkte faktiskt inte så långt. Bra tillägg!

2023-01-16 18:36 UTC, Zaai90 approved these changes

2023-01-16 18:39 UTC, Zaai90 approved these changes

2023-01-16 18:39 UTC, Zaai90 commented on backend/Api/Controllers/v1/CustomerChoreController.cs
> +    [HttpPatch]
```suggestion
    [HttpPut]
```

2023-01-16 18:42 UTC, merged